{"name": "test_get_test_plan_exception", "status": "passed", "description": "Test get test plan exception.", "start": 1743499569955, "stop": 1743499569956, "uuid": "95287b74-b599-440c-b2c2-964e87221a54", "historyId": "5c7353a3a1765062779d6321de670593", "testCaseId": "5c7353a3a1765062779d6321de670593", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_test_plan_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}