{"name": "test_get_test_suite_exception", "status": "passed", "description": "Test retrieval with an exception caused by the API.", "attachments": [{"name": "log", "source": "83f19444-90c4-4e49-b883-22d8e59aff3b-attachment.txt", "type": "text/plain"}], "start": 1743501666290, "stop": 1743501666291, "uuid": "0dbea263-f6b0-4a14-8914-eae187b502f1", "historyId": "f94de1422cb3d7ae4746b5a46b3f693e", "testCaseId": "f94de1422cb3d7ae4746b5a46b3f693e", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_get_test_suite_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}