{"name": "test_delete_test_plan_exception", "status": "passed", "description": "Test deletion of a test plan with exception in logger.", "start": 1743504726478, "stop": 1743504726479, "uuid": "3ffda05e-952f-4e03-8ec1-bbec56da394f", "historyId": "3ab29d7364a6bfef61d3a9c0dffa4ba8", "testCaseId": "3ab29d7364a6bfef61d3a9c0dffa4ba8", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_delete_test_plan_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}