{"name": "test_get_test_suite_logs_error", "status": "passed", "description": "Test logger called when retrieval of a single test suite fails.", "start": 1743499569995, "stop": 1743499569996, "uuid": "68f21153-bd33-4fc5-b9a2-c9fc65c13e7d", "historyId": "8b7d7a626dbe5602c3040da537f73eb7", "testCaseId": "8b7d7a626dbe5602c3040da537f73eb7", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_test_suite_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}