{"name": "test_get_test_suite_logs_error", "status": "passed", "description": "Test logger called when retrieval of a single test suite fails.", "start": 1743501666420, "stop": 1743501666421, "uuid": "e4b72401-4b2a-4219-8e6b-2f55778c62c6", "historyId": "8b7d7a626dbe5602c3040da537f73eb7", "testCaseId": "8b7d7a626dbe5602c3040da537f73eb7", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_test_suite_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}