{"name": "test_get_all_test_suites_logs_error", "status": "passed", "description": "Test logger called when retrieval of all test suites fails.", "start": 1743504726544, "stop": 1743504726544, "uuid": "89ff2a32-f9f4-4d32-acbe-06282a558abb", "historyId": "668eb79671db0515f0d48793ef24a536", "testCaseId": "668eb79671db0515f0d48793ef24a536", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_all_test_suites_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}