{"name": "test_delete_test_suite_exception", "status": "passed", "description": "Test deletion with an exception caused by the API", "attachments": [{"name": "log", "source": "00215f2b-b39b-4659-b1a3-5cf911593e0f-attachment.txt", "type": "text/plain"}], "start": 1743504726376, "stop": 1743504726376, "uuid": "198f04c9-3921-4933-b786-6493318dabc1", "historyId": "0e0acc98e882819ce78d9eff96208e6d", "testCaseId": "0e0acc98e882819ce78d9eff96208e6d", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_delete_test_suite_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}