{"name": "test_get_test_plans_exception", "status": "passed", "description": "Test get test plans exception.", "start": 1743499569965, "stop": 1743499569966, "uuid": "e7cdfa93-a000-40cc-8233-92811c0ef1ca", "historyId": "b55d4279968a6224b45db33da6677ffb", "testCaseId": "b55d4279968a6224b45db33da6677ffb", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_test_plans_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}