{"name": "test_add_test_case_logs_error", "status": "passed", "description": "Test logger called when addition of test cases fails.", "start": 1743499570015, "stop": 1743499570016, "uuid": "e0f79a50-9688-4759-bf6d-cddcbe1ae73d", "historyId": "14a2ea932e5d2d538f59e40733927f7e", "testCaseId": "14a2ea932e5d2d538f59e40733927f7e", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_add_test_case_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}