{"name": "test_delete_test_suite_exception", "status": "passed", "description": "Test deletion with an exception caused by the API", "attachments": [{"name": "log", "source": "265bc357-8dfa-49a0-b91e-507699185383-attachment.txt", "type": "text/plain"}], "start": 1743501666271, "stop": 1743501666271, "uuid": "813a299b-a6be-4aef-9447-e549a7bb1c65", "historyId": "0e0acc98e882819ce78d9eff96208e6d", "testCaseId": "0e0acc98e882819ce78d9eff96208e6d", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_delete_test_suite_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}