{"name": "test_create_work_item_api_error_unknown_value", "status": "passed", "description": "Test create_work_item when the connection fails with 'unknown error'.", "start": 1743504727967, "stop": 1743504727967, "uuid": "53f98313-4deb-4bc2-950d-1f68d968ff72", "historyId": "d8ac725fd166a3d675bf567ea0881e0a", "testCaseId": "d8ac725fd166a3d675bf567ea0881e0a", "fullName": "src.tests.ado.work_item.test_unit_ado_wrapper.TestAdoWorkItemWrapper#test_create_work_item_api_error_unknown_value", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.work_item"}, {"name": "suite", "value": "test_unit_ado_wrapper"}, {"name": "subSuite", "value": "TestAdoWorkItemWrapper"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.work_item.test_unit_ado_wrapper"}]}