{"name": "test_delete_test_suite_exception", "status": "passed", "description": "Test deletion with an exception caused by the API", "attachments": [{"name": "log", "source": "77540740-f288-4eae-9f18-601ff6da77b0-attachment.txt", "type": "text/plain"}], "start": 1743505054874, "stop": 1743505054875, "uuid": "bf37d0a0-a071-4264-876e-956975e4fa5b", "historyId": "0e0acc98e882819ce78d9eff96208e6d", "testCaseId": "0e0acc98e882819ce78d9eff96208e6d", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_delete_test_suite_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}