{"name": "test_get_test_plan_exception", "status": "passed", "description": "Test get test plan exception.", "start": 1743504726489, "stop": 1743504726490, "uuid": "686f9cf1-8971-4ec4-aab3-be920ddf789f", "historyId": "5c7353a3a1765062779d6321de670593", "testCaseId": "5c7353a3a1765062779d6321de670593", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_get_test_plan_exception", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}