{"name": "test_get_all_test_suites_exception", "status": "passed", "description": "Test retrieval of all test suites with an exception caused by the API.", "attachments": [{"name": "log", "source": "d4baeaf3-fb3f-4441-9540-4b07530ec41c-attachment.txt", "type": "text/plain"}], "start": 1743504726405, "stop": 1743504726406, "uuid": "9b0f24f3-69aa-4463-a5c9-36007886acbe", "historyId": "fc07bc7ff31acdc49e93ffc8d9f5495e", "testCaseId": "fc07bc7ff31acdc49e93ffc8d9f5495e", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_get_all_test_suites_exception", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}