{"name": "test_get_test_case_invalid", "status": "passed", "description": "Test retrieval with an error caused by the API.", "attachments": [{"name": "log", "source": "8ff02a48-b52e-419f-8fa1-cd43b5157246-attachment.txt", "type": "text/plain"}], "start": 1743501666330, "stop": 1743501666330, "uuid": "5cdef1db-6383-4d2b-b353-b7462b03ac28", "historyId": "1770d75ee88316b20b505555e260487c", "testCaseId": "1770d75ee88316b20b505555e260487c", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_get_test_case_invalid", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az2032-69"}, {"name": "thread", "value": "2321-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}